version: "3.3"
services:
  server:
    container_name: unleash-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    environment:
      GOOGLE_CLIENT_ID: 
      GOOGLE_CLIENT_SECRET: 
      GOOGLE_CALLBACK_URL: 
      WHITELISTED_DOMAIN: 
      DATABASE_URL: postgres://postgres:unleash@db/postgres
      UNLEASH_URL: "http://server:4242/api/"
      UNLEASH_APP_NAME: "demo-feature-toggle"
      UNLEASH_REFRESH_INTERVAL: 1000
    depends_on:
      - db
    command: >
      sh -c "
        while ! nc -z db 5432; do
          echo 'Postgres is unavailable.'
          sleep 1
        done
        npm run start"
    volumes:
      - ./server:/src
      
  db:
    container_name: unleash-database
    expose:
      - "5432"
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  client:
    container_name: unleash-client
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_UNLEASH_API: http://localhost:4242/features
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
